title: SOLUTIONQLOUD Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status-solutioncloud.de/
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Hosting
      category: General Datacenter Frankfurt am Main
    - name: Colocation
      category: General Datacenter Frankfurt am Main
    - name: Infrastructure Frankfurt
      description: ""
      category: General Datacenter Frankfurt am Main
      link: https://example.com/
    - name: Internet Connection Frankfurt
      description: ""
      category: General Datacenter Frankfurt am Main
    - name: Remote Desktop Gateway
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Connection Service
    - name: Internet Connection Frankfurt
      category: Connection Service
    - name: Client VPN
      category: Connection Service
    - name: nFactor Authentication
      category: Connection Service
    - name: Location Connect
      category: Connection Service
    - name: Webhosting
      category: SOLUTIONQLOUD Hosting
    - name: Domainhosting
      category: SOLUTIONQLOUD Hosting
    - name: Storage Cluster Service Frankfurt
      category: SOLUTIONQLOUD Hosting
    - name: Server Cluster Service Frankfurt
      category: SOLUTIONQLOUD Hosting
    - name: Infrastructure Frankfurt
      category: SOLUTIONQLOUD Hosting
    - name: Internet Connection Frankfurt
      category: SOLUTIONQLOUD Hosting
    - name: Client VPN
      category: SOLUTIONQLOUD Hosting
    - name: nFactor Authentication
      category: SOLUTIONQLOUD Hosting
    - name: Location Connect
      category: SOLUTIONQLOUD Hosting
    - name: Remote Desktop Gateway
      category: SOLUTIONQLOUD Colocation
    - name: Infrastructure Frankfurt
      description: ""
      category: SOLUTIONQLOUD Colocation
    - name: Client VPN
      category: SOLUTIONQLOUD Colocation
    - name: nFactor Authentication
      category: SOLUTIONQLOUD Colocation
    - name: Location Connect
      category: SOLUTIONQLOUD Colocation
    - category: SOLUTIONQLOUD Dedicated
      name: RADIX Server
    - name: Managed Backup
      category: Backup Service
    - name: HandsOn Backup
      category: Backup Service
    - name: Hosted Exchange Service
      category: E-Mail Service
    - name: Hosted Mail Service
      category: E-Mail Service
    - name: E-Mail Antispam Service
      category: E-Mail Service
    - name: E-Mail Archive
      category: E-Mail Service
    - name: Telephone System Frankfurt
      category: Telephone System
    - name: SIP Trunk Provider
      category: Telephone System
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#f2e01c"
  enableLastMod: true
  headerTextColor: white
  logo: /img/lxed5oe0rlrc.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#ffffff"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: General Datacenter Frankfurt am Main
      description: ""
      closed: true
    - name: Connection Service
      closed: true
    - name: SOLUTIONQLOUD Hosting
      untitled: false
      closed: true
    - name: SOLUTIONQLOUD Colocation
      closed: true
    - name: SOLUTIONQLOUD Dedicated
      closed: true
    - name: Backup Service
      closed: true
    - name: E-Mail Service
      closed: true
    - name: Telephone System
      closed: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
